// frontend/src/pages/admin/user-roles/create.vue
<template>
  <div>
    <admin-page-header :title="$t('models.user_role.title_one')">
      <template #actions>
        <ui-button @click="form.onSubmit()">Сохранить</ui-button>
      </template>
    </admin-page-header>
    <vesp-form ref="form" url="admin/user-roles" method="put" :schema="schema" :initial-values="initialValues">
      <template #form-fields>
        <forms-user-role />
      </template>
    </vesp-form>
  </div>
</template>

<script setup lang="ts">
import { markRaw } from 'vue'
import { object, string } from 'yup'

const form = ref()
const schema = markRaw(object({ title: string().required() }))
const initialValues = markRaw({
  id: 0,
  title: '',
  scope: []
})
</script>

// frontend/src/app/admin/(private)/user-roles/create/page.tsx
import { PageHeader, PageHeaderProps } from '@/components/admin/PageHeader'
import {
  UserRoleForm,
  UserRoleFormFields,
  UserRoleFormSchema
} from '@/components/admin/UserRoleForm'
import { VespForm } from '@/components/admin/VespForm'
import { VespFormSubmit } from '@/components/admin/VespFormSubmit'
import { Button } from '@/components/ui/button'
import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Добавить роль'
}

export default function Page() {
  const data = {
    title: '',
    scope: []
  }

  const actions: PageHeaderProps['actions'] = [
    <Link href="/admin/user-roles" key="back">
      <Button variant="secondary">Отмена</Button>
    </Link>,
    <VespFormSubmit key="submit">Сохранить</VespFormSubmit>
  ]

  return (
    <VespForm<UserRoleFormFields>
      url="admin/user-roles"
      method="PUT"
      schema={UserRoleFormSchema}
      defaultValues={data}
    >
      <PageHeader title={`${metadata.title}`} actions={actions} />
      <UserRoleForm />
    </VespForm>
  )
}
